spring.config.import=optional:file:.env
spring.application.name=cc
spring.datasource.url=jdbc:postgresql://localhost:5432/ccdb
spring.datasource.username=postgres
spring.datasource.password=iamhim


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


